---
- name: Install
  yum:
    name: "prometheus2"
    state: present
    disable_gpg_check: true
  register: install_packages
  until: install_packages is success
  ignore_errors: "{{ ansible_check_mode }}"
  retries: 5
  delay: 2
...
