---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - install
    - configure

- name: "Prometheus: checks"
  include_tasks: preflight.yml
  tags:
    - configure

- block:
    - name: "Prometheus: install"
      include_tasks: "install/{{ ansible_distribution }}.yml"
      tags: install

    - name: 'Prometheus: Create systemd service configuration directory'
      file:
        path: /etc/systemd/system/prometheus.service.d
        state: directory
        owner: root
        group: root
        mode: 0755
      tags: configure

    - name: "Prometheus: configure systemd service limits"
      ini_file:
        path: /etc/systemd/system/prometheus.service.d/limits.conf
        section: 'Service'
        option: '{{ item.key }}'
        value: '{{ item.value }}'
        backup: true
      with_dict: '{{ prometheus_systemd_limits }}'
      tags: configure

    - name: "Prometheus: configure"
      include_tasks: "configure.yml"
      tags: configure

    - name: "Prometheus: setup netdata"
      template:
        src: netdata.yml.j2
        dest: "{{ prometheus_conf_dir }}/targets/netdata.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      register: _netdata_conf
      tags: configure
  when: inventory_hostname in prometheus_admin_hosts

- name: "Prometheus: setup healthchecks"
  include_tasks: "healthchecks.yml"
  when: prometheus_blackbox_enabled
  tags: configure

- block:
    - name: "Prometheus: (re)start service"
      systemd:
        state: "{{ 'started' if prometheus_provision_only else 'restarted' }}"
        daemon_reload: true
        enabled: "{{ prometheus_systemd_enabled }}"
        name: "prometheus"
      tags: configure

    - name: "Prometheus: wait for service to be up"
      wait_for:
        host: "{{ prometheus_bind_address }}"
        port: "{{ prometheus_bind_port }}"
        delay: 10
      tags: configure
  when:
    - inventory_hostname in prometheus_admin_hosts
    - _netdata_conf is changed or _prometheus_conf is changed or _prometheus_defaults is changed
     or _prometheus_dirs is changed or _prometheus_aggr is changed
     or _prometheus_healthchecks is changed or _prometheus_alerts is changed
...
