---
- name: Preflight > init checks
  set_fact:
    prometheus_checks:
      - distro: false
      - inventory_file: true
      - monitored_hosts: true
  tags: configure

- name: Preflight > check that at least one monitored host is defined
  set_fact:
    prometheus_checks: "{{ prometheus_checks | combine({'monitored_hosts': false}) }}"
  when:
    - prometheus_blackbox_enabled
    - prometheus_monitored_hosts | length == 0
  tags: configure

- name: Preflight > check distro
  set_fact:
    prometheus_checks: "{{ prometheus_checks | combine({'distro': true}) }}"
  when:
    - ansible_distribution == item.distro
    - ansible_distribution_major_version == item.version | string
  with_items: "{{ prometheus_valid_distros }}"
  tags: configure

- name: Perform a stat on the inventory file
  stat:
    path: "/etc/oio/sds/{{ prometheus_openio_namespace }}/inventory.yml"
  register: inventory_file
  when:
    - prometheus_blackbox_enabled
    - inventory_hostname in prometheus_monitored_hosts
  tags: configure

- name: Preflight > check that all nodes have an inventory.yml file
  set_fact:
    prometheus_checks: "{{ prometheus_checks | combine({'inventory_file': false}) }}"
  when:
    - prometheus_blackbox_enabled
    - inventory_hostname in prometheus_monitored_hosts
    - not inventory_file.stat.exists
    - not ansible_check_mode
  tags: configure

# Keep this part at the end
- name: Fail on failed checks
  fail:
    msg: "Check failed: {{ item.key }}"
  when: not item.value
  with_dict: "{{ prometheus_checks }}"
  tags: configure
...
