# Test playbook
---
- name: "Test playbook using management interface and address"
  hosts: "all"
  become: true
  vars:
    namespace: TRAVIS
  pre_tasks:
    - name: Seed directory for NS
      file:
        path: "/etc/oio/sds/{{ namespace }}"
        state: directory
    - name: Seed inventory on nodes
      copy:
        src: inventory.yml
        dest: "/etc/oio/sds/{{ namespace }}/inventory.yml"
    - name: Setup networking
      set_fact:
        openio_bind_mgmt_address: "{{ ansible_eth1.ipv4.address }}"
        openio_bind_mgmt_interface: "eth1"
        openio_bind_address: "{{ ansible_default_ipv4.address }}"
  roles:
    - role: repo
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: role_under_test
      prometheus_netdata_group: all
      prometheus_admin_hosts: [ 'localhost' ]
      prometheus_monitored_hosts: [ 'localhost', 'localhost' ]
...
